version: 2.1
jobs:
  test:
    docker:
      - image: node:14.14.0
        environment:
          NODE_ENV: test
          ROOT_DIR: $CIRCLE_WORKING_DIRECTORY
    steps:
      - checkout
      - restore_cache:
          keys:
            - mongo-{{ checksum "script/docker/mongo-setup" }}
            - mongo-
      - run: script/docker/mongo-setup
      - save_cache:
          key: mongo-{{ checksum "script/docker/mongo-setup" }}
          paths:
            - /usr/local/bin/mongo
      - restore_cache:
          keys:
            - yarn-lock-{{ checksum "yarn.lock" }}
            - yarn-lock-
      - run: yarn install --cache-folder ~/.cache/yarn
      - save_cache:
          key: yarn-lock-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ~/.cache/yarn
      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run Tests
          command: |
            ./cc-test-reporter before-build
            yarn jest --ci --runInBand --reporters=default --reporters=jest-junit
            ./cc-test-reporter after-build --coverage-input-type lcov --exit-code "$?"
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit

workflows:
  test:
    jobs:
      - test
