version: 2.1
orbs:
  docker: circleci/docker@2.0.3
jobs:
  test:
    resource_class: small
    docker:
      - image: node:18.7.0
        environment:
          APP_ENV: test
          NODE_ENV: test
          ROOT_DIR: $CIRCLE_WORKING_DIRECTORY
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-lock-{{ checksum "package-lock.json" }}
            - npm-lock-
      - run: npm install --cache ~/.cache/npm
      - save_cache:
          key: npm-lock-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            - ~/.cache/npm
      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run Tests
          command: |
            ./cc-test-reporter before-build
            npx jest --ci --runInBand --reporters=default --reporters=jest-junit
            ./cc-test-reporter after-build --coverage-input-type lcov --exit-code "$?"
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit
  lint-docker:
    resource_class: small
    executor: docker/hadolint
    steps:
      - checkout
      - docker/hadolint:
          dockerfiles: 'Dev.dockerfile:Prod.dockerfile'
  build:
    executor: docker/docker
    steps:
      - setup_remote_docker:
          version: 20.10.11
      - checkout
      - docker/build:
          dockerfile: Prod.dockerfile
          image: bnsfly/audiobook-catalog
          tag: 'git-<< pipeline.git.revision >>'
  build-and-publish:
    resource_class: small
    executor: docker/docker
    steps:
      - setup_remote_docker:
          version: 20.10.11
      - checkout
      - run: echo << pipeline.git.tag >>
      - run:
          name: Docker Login
          command: |
            set -e
            echo "$DOCKER_ACCESS_TOKEN" | docker login --username bnsfly --password-stdin
      - docker/build:
          dockerfile: Prod.dockerfile
          image: bnsfly/audiobook-catalog
          tag: '<< pipeline.git.tag >>,latest'
      - docker/push:
          image: bnsfly/audiobook-catalog
          tag: '<< pipeline.git.tag >>,latest'

workflows:
  version: 2
  test-and-build:
    jobs:
      - test:
          filters:
            tags:
              ignore: /^v.*/
      - lint-docker:
          filters:
            tags:
              ignore: /^v.*/
      - build:
          requires:
            - lint-docker
  test-and-publish:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - lint-docker:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - build-and-publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - lint-docker
            - test
