version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:14.14.0
        environment:
          NODE_ENV: test
          ROOT_DIR: $CIRCLE_WORKING_DIRECTORY
    steps:
      - checkout
      - restore_cache:
          keys:
            - mongo-{{ checksum "script/docker/mongo-setup" }}
            - mongo-
      - run: script/docker/mongo-setup
      - save_cache:
          key: mongo-{{ checksum "script/docker/mongo-setup" }}
          paths:
            - /usr/local/bin/mongo
      - restore_cache:
          keys:
            - yarn-lock-{{ checksum "yarn.lock" }}
            - yarn-lock-
      - run: yarn install --cache-folder ~/.cache/yarn
      - save_cache:
          key: yarn-lock-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ~/.cache/yarn
      - run:
          name: Run Tests
          command: yarn jest --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit



workflows:
  test:
    jobs:
      - test
